<?php

use App\Http\Controllers\Backend\BannerController;
use App\Http\Controllers\Backend\BrendController;
use App\Http\Controllers\Backend\BrendSocialController;
use App\Http\Controllers\Backend\ContactApplyController;
use App\Http\Controllers\Backend\ContactInfoController;
use App\Http\Controllers\Backend\ContactSeoController;
use App\Http\Controllers\Backend\ContactUsController;
use App\Http\Controllers\Backend\FuelController;
use App\Http\Controllers\Backend\HomeController;
use App\Http\Controllers\Backend\HomeSeoController;
use App\Http\Controllers\Backend\LogoController;
use App\Http\Controllers\Backend\ModelController;
use App\Http\Controllers\Backend\PriceController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ProductIconController;
use App\Http\Controllers\Backend\ProductImageController;
use App\Http\Controllers\Backend\SocialController;
use App\Http\Controllers\Backend\SocialShareController;
use App\Http\Controllers\Backend\StatusController;
use App\Http\Controllers\Backend\SuccessSeoController;
use App\Http\Controllers\Backend\TestDriveController;
use App\Http\Controllers\Backend\TranslationController;
use App\Http\Controllers\Backend\FeatureGroupController;
use App\Http\Controllers\Backend\SuccessController;
use App\Http\Controllers\OfferController;
use Illuminate\Support\Facades\Route;

Route::resource('brend', BrendController::class);
Route::resource('fuel', FuelController::class);
Route::resource('model', ModelController::class);
Route::resource('product', ProductController::class);
Route::resource('product-icon', ProductIconController::class);
Route::resource('product-image', ProductImageController::class);
Route::resource('banner', BannerController::class);
Route::resource('social', SocialController::class);
Route::resource('share', SocialShareController::class);
Route::resource('logo', LogoController::class);
Route::resource('translation', TranslationController::class);
Route::resource('test-drive', TestDriveController::class);
Route::resource('home', HomeController::class);
Route::resource('price', PriceController::class);
Route::post('/offer/destroy', [OfferController::class, 'destroy']);
Route::resource('offer', OfferController::class)->except('destroy');
Route::resource('feature-groups', FeatureGroupController::class);
Route::resource('success',SuccessController::class);
Route::resource('status',StatusController::class);
Route::resource('contact-info',ContactInfoController::class);
Route::resource('contact-apply',ContactApplyController::class);
Route::resource('contactDetail',ContactUsController::class);
Route::resource('brend-social',BrendSocialController::class);
Route::resource('home-seo',HomeSeoController::class);
Route::resource('contact-seo',ContactSeoController::class);
Route::resource('success-seo',SuccessSeoController::class);
Route::get('resume/download',[ProductController::class,'resumeDownload'])->name('resume.download');
